user:
    resource:
        path: ../src/User/
        namespace: App\User\Infrastructure\Http\Controller
    type: attribute

category:
    resource:
        path: ../src/Category/
        namespace: App\Category\Infrastructure\Http\Controller
    type: attribute

task:
    resource:
        path: ../src/Task/
        namespace: App\Task\Infrastructure\Http\Controller
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

api_login:
    path: /api/login