security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\User\Domain\User
                property: email

    firewalls:
        jwt:
            provider: app_user_provider
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: api_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: '^/api/login', roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: '^/api/user', roles: PUBLIC_ACCESS, methods: [POST] }
        - { path: '^/api/doc', roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: '^/', role: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
